@echo off
echo Starting API with enhanced debugging using HTTP profile...

set ASPNETCORE_ENVIRONMENT=Development
set ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=false
set ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Debug
set ASPNETCORE_LOGGING__LOGLEVEL__MICROSOFT=Debug
set ASPNETCORE_LOGGING__LOGLEVEL__MICROSOFT.ASPNETCORE=Debug
set ASPNETCORE_LOGGING__LOGLEVEL__MICROSOFT.ENTITYFRAMEWORKCORE=Debug
set DOTNET_ENVIRONMENT=Development

cd HospitalManagement.API
dotnet build
dotnet run --launch-profile "http"

pause
